<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Soundboard.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Soundboard.Core.Tests" />
  </ItemGroup>

</Project>
